### ISSUE TITLE
Depend on `openff-toolkit-base`?

### ISSUE THREAD

**Issue by mattwthompson** [conda-forge/openff-nagl-feedstock#6]
### Comment:

Would you consider a change of `'s/openff-toolkit/openff-toolkit-base/'`? It'd be nice to be able to use NAGL alongside RDKit and/or OpenEye Toolkits but without AmberTools.

I poked around the repo (of the source code, not the feedstock) and didn't find any obvious AmberTools dependency. Not sure if there are other technical details.

**Comment by mattwthompson** [comment]
Sweet - I'm happy to handle this myself if you haven't already started

**Comment by lilyminium** [comment]
Ah no please go ahead -- thank you!

**Comment by lilyminium** [comment]
Fixed by #11!
